version: 2.1

orbs:
  macos: circleci/macos@2.3.4
  ruby: circleci/ruby@2.0.0

jobs:
  build-and-test:
    macos:
      xcode: 14.2.0
    resource_class: macos.x86.medium.gen2
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - macos/switch-ruby:
          version: "3.1.3"
      - ruby/install-deps # instead of bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane test
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  build-test:
    jobs:
      - build-and-test
